name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          # args: --interaction=nonstopmode
      - name: push changes to remote
        run: |
          git config --global user.name "akss13"
          git config --global user.email "aakarsh.s.saini@gmail.com"
          git add main.pdf
          git commit -a -m "pdf file commit from action"
          git push

