name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Github Action for LaTeX
    uses: xu-cheng/latex-action@v2
    with:
    # The root LaTeX file to be compiled
    root_file: deedy_resume-openfont.tex
    # The working directory for the LaTeX engine
    #    working_directory: # optional
    # The LaTeX engine to be invoked
    #    compiler: # optional, default is latexmk
    # Extra arguments to be passed to the LaTeX engine
    #    args: # optional, default is -pdf -file-line-error -halt-on-error -interaction=nonstopmode
    # [Deprecated] Install extra packages by tlmgr
    #    extra_packages: # optional
    # Install extra packages by apk
    #    extra_system_packages: # optional
    # Arbitrary bash codes to be executed before compiling LaTeX documents
    #    pre_compile: # optional
    # Arbitrary bash codes to be executed after compiling LaTeX documents
    #    post_compile: # optional
    # Instruct latexmk to enable --shell-escape
    #    latexmk_shell_escape: # optional
    # Instruct latexmk to use LuaLaTeX
    #    latexmk_use_lualatex: # optional
    # Instruct latexmk to use XeLaTeX
    latexmk_use_xelatex: true
